package com.vector.pojo;
// Generated 2018-6-2 10:50:07 by Hibernate Tools 4.3.1



/**
 * BackpackSetting generated by hbm2java
 */
public class BackpackSetting  implements java.io.Serializable {


     private int backpackSettingId;
     private String backpackSqlFile;
     private String backpackBatFile;
     private String backpackToPath;

    public BackpackSetting() {
    }

    public BackpackSetting(int backpackSettingId, String backpackSqlFile, String backpackBatFile, String backpackToPath) {
       this.backpackSettingId = backpackSettingId;
       this.backpackSqlFile = backpackSqlFile;
       this.backpackBatFile = backpackBatFile;
       this.backpackToPath = backpackToPath;
    }
   
    public int getBackpackSettingId() {
        return this.backpackSettingId;
    }
    
    public void setBackpackSettingId(int backpackSettingId) {
        this.backpackSettingId = backpackSettingId;
    }
    public String getBackpackSqlFile() {
        return this.backpackSqlFile;
    }
    
    public void setBackpackSqlFile(String backpackSqlFile) {
        this.backpackSqlFile = backpackSqlFile;
    }
    public String getBackpackBatFile() {
        return this.backpackBatFile;
    }
    
    public void setBackpackBatFile(String backpackBatFile) {
        this.backpackBatFile = backpackBatFile;
    }
    public String getBackpackToPath() {
        return this.backpackToPath;
    }
    
    public void setBackpackToPath(String backpackToPath) {
        this.backpackToPath = backpackToPath;
    }




}


