package com.vector.pojo;
// Generated 2018-6-2 10:50:07 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * BackpackFile generated by hbm2java
 */
public class BackpackFile  implements java.io.Serializable {


     private int backpackFileId;
     private Serializable backpackFilePath;
     private Date backpackTime;

    public BackpackFile() {
    }

    public BackpackFile(int backpackFileId, Serializable backpackFilePath, Date backpackTime) {
       this.backpackFileId = backpackFileId;
       this.backpackFilePath = backpackFilePath;
       this.backpackTime = backpackTime;
    }
   
    public int getBackpackFileId() {
        return this.backpackFileId;
    }
    
    public void setBackpackFileId(int backpackFileId) {
        this.backpackFileId = backpackFileId;
    }
    public Serializable getBackpackFilePath() {
        return this.backpackFilePath;
    }
    
    public void setBackpackFilePath(Serializable backpackFilePath) {
        this.backpackFilePath = backpackFilePath;
    }
    public Date getBackpackTime() {
        return this.backpackTime;
    }
    
    public void setBackpackTime(Date backpackTime) {
        this.backpackTime = backpackTime;
    }




}


