package com.vector.pojo;
// Generated 2018-6-2 10:50:07 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * BackpackSetting generated by hbm2java
 */
public class BackpackSetting  implements java.io.Serializable {


     private int backpackSettingId;
     private Serializable backpackSqlFile;
     private Serializable backpackBatFile;
     private Serializable backpackToPath;

    public BackpackSetting() {
    }

    public BackpackSetting(int backpackSettingId, Serializable backpackSqlFile, Serializable backpackBatFile, Serializable backpackToPath) {
       this.backpackSettingId = backpackSettingId;
       this.backpackSqlFile = backpackSqlFile;
       this.backpackBatFile = backpackBatFile;
       this.backpackToPath = backpackToPath;
    }
   
    public int getBackpackSettingId() {
        return this.backpackSettingId;
    }
    
    public void setBackpackSettingId(int backpackSettingId) {
        this.backpackSettingId = backpackSettingId;
    }
    public Serializable getBackpackSqlFile() {
        return this.backpackSqlFile;
    }
    
    public void setBackpackSqlFile(Serializable backpackSqlFile) {
        this.backpackSqlFile = backpackSqlFile;
    }
    public Serializable getBackpackBatFile() {
        return this.backpackBatFile;
    }
    
    public void setBackpackBatFile(Serializable backpackBatFile) {
        this.backpackBatFile = backpackBatFile;
    }
    public Serializable getBackpackToPath() {
        return this.backpackToPath;
    }
    
    public void setBackpackToPath(Serializable backpackToPath) {
        this.backpackToPath = backpackToPath;
    }




}


