package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable{


     private int billId;
     private Patient patient;
     private String paymentStatus;
     private Date billDate;
     private Double totalAmount;
     private Set checkRecords = new HashSet(0);

    public Bill() {
    }

	
    public Bill(int billId, Patient patient, String paymentStatus, Date billDate) {
        this.billId = billId;
        this.patient = patient;
        this.paymentStatus = paymentStatus;
        this.billDate = billDate;
    }
    public Bill(int billId, Patient patient, String paymentStatus, Date billDate, Double totalAmount, Set checkRecords) {
       this.billId = billId;
       this.patient = patient;
       this.paymentStatus = paymentStatus;
       this.billDate = billDate;
       this.totalAmount = totalAmount;
       this.checkRecords = checkRecords;
    }
   
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public Date getBillDate() {
        return this.billDate;
    }
    
    public void setBillDate(Date billDate) {
        this.billDate = billDate;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Set getCheckRecords() {
        return this.checkRecords;
    }
    
    public void setCheckRecords(Set checkRecords) {
        this.checkRecords = checkRecords;
    }




}


