package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * BloodBank generated by hbm2java
 */
public class BloodBank  implements java.io.Serializable {


     private int recordId;
     private String donorName;
     private String donorBloodType;
     private String donorGender;
     private String donorAddress;
     private String donorPhone;
     private String isInBank;

    public BloodBank() {
    }

    public BloodBank(int recordId, String donorName, String donorBloodType, String donorGender, String donorAddress, String donorPhone, String isInBank) {
       this.recordId = recordId;
       this.donorName = donorName;
       this.donorBloodType = donorBloodType;
       this.donorGender = donorGender;
       this.donorAddress = donorAddress;
       this.donorPhone = donorPhone;
       this.isInBank = isInBank;
    }
   
    public int getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(int recordId) {
        this.recordId = recordId;
    }
    public String getDonorName() {
        return this.donorName;
    }
    
    public void setDonorName(String donorName) {
        this.donorName = donorName;
    }
    public String getDonorBloodType() {
        return this.donorBloodType;
    }
    
    public void setDonorBloodType(String donorBloodType) {
        this.donorBloodType = donorBloodType;
    }
    public String getDonorGender() {
        return this.donorGender;
    }
    
    public void setDonorGender(String donorGender) {
        this.donorGender = donorGender;
    }
    public String getDonorAddress() {
        return this.donorAddress;
    }
    
    public void setDonorAddress(String donorAddress) {
        this.donorAddress = donorAddress;
    }
    public String getDonorPhone() {
        return this.donorPhone;
    }
    
    public void setDonorPhone(String donorPhone) {
        this.donorPhone = donorPhone;
    }
    public String getIsInBank() {
        return this.isInBank;
    }
    
    public void setIsInBank(String isInBank) {
        this.isInBank = isInBank;
    }




}


