package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CheckItem generated by hbm2java
 */
public class CheckItem  implements java.io.Serializable {


     private int checkItemId;
     private String checkItemName;
     private double checkItemPrice;
     private String checkItemDescription;
     private Set checkResults = new HashSet(0);
     private Set checkRecords = new HashSet(0);

    public CheckItem() {
    }

	
    public CheckItem(int checkItemId, String checkItemName, double checkItemPrice, String checkItemDescription) {
        this.checkItemId = checkItemId;
        this.checkItemName = checkItemName;
        this.checkItemPrice = checkItemPrice;
        this.checkItemDescription = checkItemDescription;
    }
    public CheckItem(int checkItemId, String checkItemName, double checkItemPrice, String checkItemDescription, Set checkResults, Set checkRecords) {
       this.checkItemId = checkItemId;
       this.checkItemName = checkItemName;
       this.checkItemPrice = checkItemPrice;
       this.checkItemDescription = checkItemDescription;
       this.checkResults = checkResults;
       this.checkRecords = checkRecords;
    }
   
    public int getCheckItemId() {
        return this.checkItemId;
    }
    
    public void setCheckItemId(int checkItemId) {
        this.checkItemId = checkItemId;
    }
    public String getCheckItemName() {
        return this.checkItemName;
    }
    
    public void setCheckItemName(String checkItemName) {
        this.checkItemName = checkItemName;
    }
    public double getCheckItemPrice() {
        return this.checkItemPrice;
    }
    
    public void setCheckItemPrice(double checkItemPrice) {
        this.checkItemPrice = checkItemPrice;
    }
    public String getCheckItemDescription() {
        return this.checkItemDescription;
    }
    
    public void setCheckItemDescription(String checkItemDescription) {
        this.checkItemDescription = checkItemDescription;
    }
    public Set getCheckResults() {
        return this.checkResults;
    }
    
    public void setCheckResults(Set checkResults) {
        this.checkResults = checkResults;
    }
    public Set getCheckRecords() {
        return this.checkRecords;
    }
    
    public void setCheckRecords(Set checkRecords) {
        this.checkRecords = checkRecords;
    }




}


