package com.vector.pojo;
// Generated 2018-5-29 16:00:47 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;

/**
 * CheckRecord generated by hbm2java
 */
public class CheckRecord implements java.io.Serializable {

    private int checkRecordId;
    @JsonIgnore
    private Bill bill;
    private CheckItem checkItem;
    private CheckResult checkResult;
    @JsonIgnore
    private Patient patient;
    private String paymentStatus;
    private Date checkDate;
    private Integer isChecked;

    public CheckRecord() {
    }

    public CheckRecord(int checkRecordId, Bill bill, CheckItem checkItem, CheckResult checkResult, Patient patient, String paymentStatus, Date checkDate,Integer isChecked) {
        this.checkRecordId = checkRecordId;
        this.bill = bill;
        this.checkItem = checkItem;
        this.checkResult = checkResult;
        this.patient = patient;
        this.paymentStatus = paymentStatus;
        this.checkDate = checkDate;
        this.isChecked=isChecked;
    }

    public int getCheckRecordId() {
        return this.checkRecordId;
    }

    public void setCheckRecordId(int checkRecordId) {
        this.checkRecordId = checkRecordId;
    }

    public Bill getBill() {
        return this.bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    public CheckItem getCheckItem() {
        return this.checkItem;
    }

    public void setCheckItem(CheckItem checkItem) {
        this.checkItem = checkItem;
    }

    public CheckResult getCheckResult() {
        return this.checkResult;
    }

    public void setCheckResult(CheckResult checkResult) {
        this.checkResult = checkResult;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public String getPaymentStatus() {
        return this.paymentStatus;
    }

    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public Date getCheckDate() {
        return this.checkDate;
    }

    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    public Integer getIsChecked() {
        return isChecked;
    }

    public void setIsChecked(Integer isChecked) {
        this.isChecked = isChecked;
    }

}
