package com.vector.pojo;
// Generated 2018-5-26 16:13:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * CheckItem generated by hbm2java
 */
public class CheckItem implements java.io.Serializable {

    private int checkItemId;
    private String checkItemName;
    private double checkItemPrice;
    private String checkItemDescription;
    @JsonIgnore
    private Set<CheckResult> checkResults = new HashSet<CheckResult>(0);
    @JsonIgnore
    private Set<CheckRecord> checkRecords = new HashSet<CheckRecord>(0);

    public CheckItem() {
    }

    public CheckItem(int checkItemId, String checkItemName, double checkItemPrice, String checkItemDescription) {
        this.checkItemId = checkItemId;
        this.checkItemName = checkItemName;
        this.checkItemPrice = checkItemPrice;
        this.checkItemDescription = checkItemDescription;
    }

    public CheckItem(int checkItemId, String checkItemName, double checkItemPrice, String checkItemDescription, Set<CheckResult> checkResults, Set<CheckRecord> checkRecords) {
        this.checkItemId = checkItemId;
        this.checkItemName = checkItemName;
        this.checkItemPrice = checkItemPrice;
        this.checkItemDescription = checkItemDescription;
        this.checkResults = checkResults;
        this.checkRecords = checkRecords;
    }

    public int getCheckItemId() {
        return this.checkItemId;
    }

    public void setCheckItemId(int checkItemId) {
        this.checkItemId = checkItemId;
    }

    public String getCheckItemName() {
        return this.checkItemName;
    }

    public void setCheckItemName(String checkItemName) {
        this.checkItemName = checkItemName;
    }

    public double getCheckItemPrice() {
        return this.checkItemPrice;
    }

    public void setCheckItemPrice(double checkItemPrice) {
        this.checkItemPrice = checkItemPrice;
    }

    public String getCheckItemDescription() {
        return this.checkItemDescription;
    }

    public void setCheckItemDescription(String checkItemDescription) {
        this.checkItemDescription = checkItemDescription;
    }

    public Set<CheckResult> getCheckResults() {
        return this.checkResults;
    }

    public void setCheckResults(Set<CheckResult> checkResults) {
        this.checkResults = checkResults;
    }

    public Set<CheckRecord> getCheckRecords() {
        return this.checkRecords;
    }

    public void setCheckRecords(Set<CheckRecord> checkRecords) {
        this.checkRecords = checkRecords;
    }

}
