package com.vector.pojo;
// Generated 2018-5-26 16:13:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;

/**
 * CheckResult generated by hbm2java
 */
public class CheckResult implements java.io.Serializable {

    private int checkResultId;
    private CheckItem checkItem;
    @JsonIgnore
    private MedicalRecord medicalRecord;
    @JsonIgnore
    private Patient patient;
    @JsonIgnore
    private Staff staff;
    private Date checkDate;
    private String checkResultDescription;

    public CheckResult() {
    }

    public CheckResult(int checkResultId, CheckItem checkItem, MedicalRecord medicalRecord, Patient patient, Staff staff, Date checkDate, String checkResultDescription) {
        this.checkResultId = checkResultId;
        this.checkItem = checkItem;
        this.medicalRecord = medicalRecord;
        this.patient = patient;
        this.staff = staff;
        this.checkDate = checkDate;
        this.checkResultDescription = checkResultDescription;
    }

    public int getCheckResultId() {
        return this.checkResultId;
    }

    public void setCheckResultId(int checkResultId) {
        this.checkResultId = checkResultId;
    }

    public CheckItem getCheckItem() {
        return this.checkItem;
    }

    public void setCheckItem(CheckItem checkItem) {
        this.checkItem = checkItem;
    }

    public MedicalRecord getMedicalRecord() {
        return this.medicalRecord;
    }

    public void setMedicalRecord(MedicalRecord medicalRecord) {
        this.medicalRecord = medicalRecord;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Staff getStaff() {
        return this.staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    public Date getCheckDate() {
        return this.checkDate;
    }

    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    public String getCheckResultDescription() {
        return this.checkResultDescription;
    }

    public void setCheckResultDescription(String checkResultDescription) {
        this.checkResultDescription = checkResultDescription;
    }

}
