package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private int departmentId;
     private String departmentName;
     private String departmentDescription;
     private Set medicalRecords = new HashSet(0);

    public Department() {
    }

	
    public Department(int departmentId, String departmentName, String departmentDescription) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.departmentDescription = departmentDescription;
    }
    public Department(int departmentId, String departmentName, String departmentDescription, Set medicalRecords) {
       this.departmentId = departmentId;
       this.departmentName = departmentName;
       this.departmentDescription = departmentDescription;
       this.medicalRecords = medicalRecords;
    }
   
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public String getDepartmentDescription() {
        return this.departmentDescription;
    }
    
    public void setDepartmentDescription(String departmentDescription) {
        this.departmentDescription = departmentDescription;
    }
    public Set getMedicalRecords() {
        return this.medicalRecords;
    }
    
    public void setMedicalRecords(Set medicalRecords) {
        this.medicalRecords = medicalRecords;
    }




}


