package com.vector.pojo;
// Generated 2018-5-26 16:13:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;

/**
 * DietAdvice generated by hbm2java
 */
public class DietAdvice implements java.io.Serializable {

    private int dietAdviceId;
    @JsonIgnore
    private Patient patient;
    @JsonIgnore
    private Staff staff;
    private String dietAdviceContent;
    private Date dietAdviceTime;

    public DietAdvice() {
    }

    public DietAdvice(int dietAdviceId, Patient patient, Staff staff, String dietAdviceContent, Date dietAdviceTime) {
        this.dietAdviceId = dietAdviceId;
        this.patient = patient;
        this.staff = staff;
        this.dietAdviceContent = dietAdviceContent;
        this.dietAdviceTime = dietAdviceTime;
    }

    public DietAdvice(Patient patient, Staff staff, String dietAdviceContent, Date dietAdviceTime) {
        this.patient = patient;
        this.staff = staff;
        this.dietAdviceContent = dietAdviceContent;
        this.dietAdviceTime = dietAdviceTime;
    }
    
    

    public int getDietAdviceId() {
        return this.dietAdviceId;
    }

    public void setDietAdviceId(int dietAdviceId) {
        this.dietAdviceId = dietAdviceId;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Staff getStaff() {
        return this.staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    public String getDietAdviceContent() {
        return this.dietAdviceContent;
    }

    public void setDietAdviceContent(String dietAdviceContent) {
        this.dietAdviceContent = dietAdviceContent;
    }

    public Date getDietAdviceTime() {
        return this.dietAdviceTime;
    }

    public void setDietAdviceTime(Date dietAdviceTime) {
        this.dietAdviceTime = dietAdviceTime;
    }

}
