package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private int imageId;
     private String imagePath;
     private String usePage;
     private Set patients = new HashSet(0);
     private Set staffs = new HashSet(0);

    public Image() {
    }

	
    public Image(int imageId, String imagePath) {
        this.imageId = imageId;
        this.imagePath = imagePath;
    }
    public Image(int imageId, String imagePath, String usePage, Set patients, Set staffs) {
       this.imageId = imageId;
       this.imagePath = imagePath;
       this.usePage = usePage;
       this.patients = patients;
       this.staffs = staffs;
    }
   
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public String getUsePage() {
        return this.usePage;
    }
    
    public void setUsePage(String usePage) {
        this.usePage = usePage;
    }
    public Set getPatients() {
        return this.patients;
    }
    
    public void setPatients(Set patients) {
        this.patients = patients;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


