package com.vector.pojo;
// Generated 2018-5-26 16:13:05 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

    private int imageId;
    private String imagePath;
    private String usePage;
    @JsonIgnore
    private Set<Patient> patients = new HashSet<Patient>(0);
    @JsonIgnore
    private Set<Staff> staffs = new HashSet<Staff>(0);

    public Image() {
    }

    public Image(int imageId, String imagePath) {
        this.imageId = imageId;
        this.imagePath = imagePath;
    }

    public Image(int imageId, String imagePath, String usePage, Set<Patient> patients, Set<Staff> staffs) {
        this.imageId = imageId;
        this.imagePath = imagePath;
        this.usePage = usePage;
        this.patients = patients;
        this.staffs = staffs;
    }

    public int getImageId() {
        return this.imageId;
    }

    public void setImageId(int imageId) {
        this.imageId = imageId;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getUsePage() {
        return this.usePage;
    }

    public void setUsePage(String usePage) {
        this.usePage = usePage;
    }

    public Set<Patient> getPatients() {
        return this.patients;
    }

    public void setPatients(Set<Patient> patients) {
        this.patients = patients;
    }

    public Set<Staff> getStaffs() {
        return this.staffs;
    }

    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }

}
