package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Medication generated by hbm2java
 */
public class Medication  implements java.io.Serializable {


     private int medicationId;
     private String medicationName;
     private String medicationInstructions;
     private String medicationDescription;
     private Set medicationHistories = new HashSet(0);

    public Medication() {
    }

	
    public Medication(int medicationId, String medicationName, String medicationInstructions, String medicationDescription) {
        this.medicationId = medicationId;
        this.medicationName = medicationName;
        this.medicationInstructions = medicationInstructions;
        this.medicationDescription = medicationDescription;
    }
    public Medication(int medicationId, String medicationName, String medicationInstructions, String medicationDescription, Set medicationHistories) {
       this.medicationId = medicationId;
       this.medicationName = medicationName;
       this.medicationInstructions = medicationInstructions;
       this.medicationDescription = medicationDescription;
       this.medicationHistories = medicationHistories;
    }
   
    public int getMedicationId() {
        return this.medicationId;
    }
    
    public void setMedicationId(int medicationId) {
        this.medicationId = medicationId;
    }
    public String getMedicationName() {
        return this.medicationName;
    }
    
    public void setMedicationName(String medicationName) {
        this.medicationName = medicationName;
    }
    public String getMedicationInstructions() {
        return this.medicationInstructions;
    }
    
    public void setMedicationInstructions(String medicationInstructions) {
        this.medicationInstructions = medicationInstructions;
    }
    public String getMedicationDescription() {
        return this.medicationDescription;
    }
    
    public void setMedicationDescription(String medicationDescription) {
        this.medicationDescription = medicationDescription;
    }
    public Set getMedicationHistories() {
        return this.medicationHistories;
    }
    
    public void setMedicationHistories(Set medicationHistories) {
        this.medicationHistories = medicationHistories;
    }




}


