package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String patientId;
     private Image image;
     private String patientName;
     private String patientBirthday;
     private String patientGender;
     private Integer patientAge;
     private String bloodType;
     private String patientPhone;
     private String patientAddress;
     private String patientMstatus;
     private String patientEmail;
     private String patientQuestion;
     private String patientAnswer;
     private String patientPassword;
     private Set dietAdvices = new HashSet(0);
     private Set bills = new HashSet(0);
     private Set medicalRecords = new HashSet(0);
     private Set checkResults = new HashSet(0);
     private Set precautionAdvices = new HashSet(0);
     private Set checkRecords = new HashSet(0);
     private Set medicationHistories = new HashSet(0);

    public Patient() {
    }

	
    public Patient(String patientId, String patientName, String patientBirthday, String patientGender, String patientPhone, String patientAddress, String patientMstatus, String patientEmail, String patientQuestion, String patientAnswer, String patientPassword) {
        this.patientId = patientId;
        this.patientName = patientName;
        this.patientBirthday = patientBirthday;
        this.patientGender = patientGender;
        this.patientPhone = patientPhone;
        this.patientAddress = patientAddress;
        this.patientMstatus = patientMstatus;
        this.patientEmail = patientEmail;
        this.patientQuestion = patientQuestion;
        this.patientAnswer = patientAnswer;
        this.patientPassword = patientPassword;
    }
    public Patient(String patientId, Image image, String patientName, String patientBirthday, String patientGender, Integer patientAge, String bloodType, String patientPhone, String patientAddress, String patientMstatus, String patientEmail, String patientQuestion, String patientAnswer, String patientPassword, Set dietAdvices, Set bills, Set medicalRecords, Set checkResults, Set precautionAdvices, Set checkRecords, Set medicationHistories) {
       this.patientId = patientId;
       this.image = image;
       this.patientName = patientName;
       this.patientBirthday = patientBirthday;
       this.patientGender = patientGender;
       this.patientAge = patientAge;
       this.bloodType = bloodType;
       this.patientPhone = patientPhone;
       this.patientAddress = patientAddress;
       this.patientMstatus = patientMstatus;
       this.patientEmail = patientEmail;
       this.patientQuestion = patientQuestion;
       this.patientAnswer = patientAnswer;
       this.patientPassword = patientPassword;
       this.dietAdvices = dietAdvices;
       this.bills = bills;
       this.medicalRecords = medicalRecords;
       this.checkResults = checkResults;
       this.precautionAdvices = precautionAdvices;
       this.checkRecords = checkRecords;
       this.medicationHistories = medicationHistories;
    }
   
    public String getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }
    public String getPatientName() {
        return this.patientName;
    }
    
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }
    public String getPatientBirthday() {
        return this.patientBirthday;
    }
    
    public void setPatientBirthday(String patientBirthday) {
        this.patientBirthday = patientBirthday;
    }
    public String getPatientGender() {
        return this.patientGender;
    }
    
    public void setPatientGender(String patientGender) {
        this.patientGender = patientGender;
    }
    public Integer getPatientAge() {
        return this.patientAge;
    }
    
    public void setPatientAge(Integer patientAge) {
        this.patientAge = patientAge;
    }
    public String getBloodType() {
        return this.bloodType;
    }
    
    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }
    public String getPatientPhone() {
        return this.patientPhone;
    }
    
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone;
    }
    public String getPatientAddress() {
        return this.patientAddress;
    }
    
    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress;
    }
    public String getPatientMstatus() {
        return this.patientMstatus;
    }
    
    public void setPatientMstatus(String patientMstatus) {
        this.patientMstatus = patientMstatus;
    }
    public String getPatientEmail() {
        return this.patientEmail;
    }
    
    public void setPatientEmail(String patientEmail) {
        this.patientEmail = patientEmail;
    }
    public String getPatientQuestion() {
        return this.patientQuestion;
    }
    
    public void setPatientQuestion(String patientQuestion) {
        this.patientQuestion = patientQuestion;
    }
    public String getPatientAnswer() {
        return this.patientAnswer;
    }
    
    public void setPatientAnswer(String patientAnswer) {
        this.patientAnswer = patientAnswer;
    }
    public String getPatientPassword() {
        return this.patientPassword;
    }
    
    public void setPatientPassword(String patientPassword) {
        this.patientPassword = patientPassword;
    }
    public Set getDietAdvices() {
        return this.dietAdvices;
    }
    
    public void setDietAdvices(Set dietAdvices) {
        this.dietAdvices = dietAdvices;
    }
    public Set getBills() {
        return this.bills;
    }
    
    public void setBills(Set bills) {
        this.bills = bills;
    }
    public Set getMedicalRecords() {
        return this.medicalRecords;
    }
    
    public void setMedicalRecords(Set medicalRecords) {
        this.medicalRecords = medicalRecords;
    }
    public Set getCheckResults() {
        return this.checkResults;
    }
    
    public void setCheckResults(Set checkResults) {
        this.checkResults = checkResults;
    }
    public Set getPrecautionAdvices() {
        return this.precautionAdvices;
    }
    
    public void setPrecautionAdvices(Set precautionAdvices) {
        this.precautionAdvices = precautionAdvices;
    }
    public Set getCheckRecords() {
        return this.checkRecords;
    }
    
    public void setCheckRecords(Set checkRecords) {
        this.checkRecords = checkRecords;
    }
    public Set getMedicationHistories() {
        return this.medicationHistories;
    }
    
    public void setMedicationHistories(Set medicationHistories) {
        this.medicationHistories = medicationHistories;
    }




}


