package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private String staffId;
     private Image image;
     private Title title;
     private String staffName;
     private String staffQuestion;
     private String staffAnswer;
     private int departmentId;
     private String staffPassword;
     private Set medicalRecords = new HashSet(0);
     private Set checkResults = new HashSet(0);
     private Set precautionAdvices = new HashSet(0);
     private Set dietAdvices = new HashSet(0);

    public Staff() {
    }

	
    public Staff(String staffId, Title title, String staffName, String staffQuestion, String staffAnswer, int departmentId, String staffPassword) {
        this.staffId = staffId;
        this.title = title;
        this.staffName = staffName;
        this.staffQuestion = staffQuestion;
        this.staffAnswer = staffAnswer;
        this.departmentId = departmentId;
        this.staffPassword = staffPassword;
    }
    public Staff(String staffId, Image image, Title title, String staffName, String staffQuestion, String staffAnswer, int departmentId, String staffPassword, Set medicalRecords, Set checkResults, Set precautionAdvices, Set dietAdvices) {
       this.staffId = staffId;
       this.image = image;
       this.title = title;
       this.staffName = staffName;
       this.staffQuestion = staffQuestion;
       this.staffAnswer = staffAnswer;
       this.departmentId = departmentId;
       this.staffPassword = staffPassword;
       this.medicalRecords = medicalRecords;
       this.checkResults = checkResults;
       this.precautionAdvices = precautionAdvices;
       this.dietAdvices = dietAdvices;
    }
   
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }
    public Title getTitle() {
        return this.title;
    }
    
    public void setTitle(Title title) {
        this.title = title;
    }
    public String getStaffName() {
        return this.staffName;
    }
    
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }
    public String getStaffQuestion() {
        return this.staffQuestion;
    }
    
    public void setStaffQuestion(String staffQuestion) {
        this.staffQuestion = staffQuestion;
    }
    public String getStaffAnswer() {
        return this.staffAnswer;
    }
    
    public void setStaffAnswer(String staffAnswer) {
        this.staffAnswer = staffAnswer;
    }
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public String getStaffPassword() {
        return this.staffPassword;
    }
    
    public void setStaffPassword(String staffPassword) {
        this.staffPassword = staffPassword;
    }
    public Set getMedicalRecords() {
        return this.medicalRecords;
    }
    
    public void setMedicalRecords(Set medicalRecords) {
        this.medicalRecords = medicalRecords;
    }
    public Set getCheckResults() {
        return this.checkResults;
    }
    
    public void setCheckResults(Set checkResults) {
        this.checkResults = checkResults;
    }
    public Set getPrecautionAdvices() {
        return this.precautionAdvices;
    }
    
    public void setPrecautionAdvices(Set precautionAdvices) {
        this.precautionAdvices = precautionAdvices;
    }
    public Set getDietAdvices() {
        return this.dietAdvices;
    }
    
    public void setDietAdvices(Set dietAdvices) {
        this.dietAdvices = dietAdvices;
    }




}


