package com.vector.pojo;
// Generated 2018-5-25 7:55:16 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Title generated by hbm2java
 */
public class Title  implements java.io.Serializable {


     private int titleId;
     private String titleName;
     private String titleDescription;
     private Set staffs = new HashSet(0);

    public Title() {
    }

	
    public Title(int titleId, String titleName, String titleDescription) {
        this.titleId = titleId;
        this.titleName = titleName;
        this.titleDescription = titleDescription;
    }
    public Title(int titleId, String titleName, String titleDescription, Set staffs) {
       this.titleId = titleId;
       this.titleName = titleName;
       this.titleDescription = titleDescription;
       this.staffs = staffs;
    }
   
    public int getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
    public String getTitleDescription() {
        return this.titleDescription;
    }
    
    public void setTitleDescription(String titleDescription) {
        this.titleDescription = titleDescription;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


